"""Добавлено поле edit_permission

Revision ID: 97500671c8d8
Revises: 
Create Date: 2024-12-18 17:44:56.075255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97500671c8d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_access_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_permission', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_access_request', schema=None) as batch_op:
        batch_op.drop_column('edit_permission')

    # ### end Alembic commands ###
