"""Initial migration

Revision ID: 975126972262
Revises: 
Create Date: 2024-12-05 23:37:40.501694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975126972262'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
