"""Обновление модели Report

Revision ID: f826fabafd01
Revises: 975126972262
Create Date: 2024-12-06 23:02:40.880697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f826fabafd01'
down_revision = '975126972262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_access_request', schema=None) as batch_op:
        batch_op.alter_column('access_expiration',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('access_granted_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_access_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_granted_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('access_expiration',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
